# Site settings
title: 方大米的前端随记
description: > # this means to ignore newlines until "baseurl:"
  记录自己在学习、工作中学到的一些前端知识
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sylviaf.github.io/" # the base hostname & protocol for your site
github_username:  sylviaf

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

# 多说的评论功能配置
comments:
    provider: duoshuo
    duoshuo:
      short_name: sylviaf
